set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage:
  prepare-container-instance ASSET_ROOT INSTANCE_ROOT NETWORK_SPEC \
    ENDPOINT_INDEX CONTAINER_ID
EOF
  exit 2
}

die() {
  echo "prepare-container-instance: $*" >&2
  exit 1
}

[[ ${EUID} -eq 0 ]] || die "must run as root"
[[ $# -eq 5 ]] || usage

asset_root=$(realpath "$1")
requested_root=$(realpath -m "$2")
network_spec=$(realpath "$3")
endpoint_index=$4
container_id=$5

[[ ${endpoint_index} =~ ^[0-9]+$ ]] ||
  die "endpoint index must be a non-negative integer"
[[ ${container_id} =~ ^[A-Za-z0-9_.-]+$ ]] ||
  die "container ID contains unsupported characters"
[[ -r ${asset_root}/assets.json &&
  -r ${asset_root}/container-bundle/config.json &&
  -d ${asset_root}/container-bundle/rootfs &&
  -d ${asset_root}/snix ]] ||
  die "asset root is incomplete: ${asset_root}"
[[ ! -e ${requested_root} ]] ||
  die "refusing to replace existing instance: ${requested_root}"

parent=$(dirname "${requested_root}")
name=$(basename "${requested_root}")
mkdir -p "${parent}"
parent=$(realpath "${parent}")
instance_root="${parent}/${name}"

run_container=@RUN_CONTAINER@
run_snix=@RUN_SNIX@
manage_network=@MANAGE_NETWORK@
runsc=@RUNSC@

endpoint=$(jq -ce --argjson index "${endpoint_index}" \
  '.endpoints[$index] | select(.kind == "netns")' \
  "${network_spec}") ||
  die "endpoint is absent or is not a network namespace"
namespace=$(jq -r '.namespace' <<<"${endpoint}")
address=$(jq -r '.address' <<<"${endpoint}")
address=${address%/*}

container_pid=
endpoint_active=false
store_mounted=false
preparation_complete=false

stop_process_group() {
  local pid=$1
  local deadline
  kill -TERM -- "-${pid}" 2>/dev/null || true
  deadline=$((SECONDS + 10))
  while kill -0 "${pid}" 2>/dev/null && ((SECONDS < deadline)); do
    sleep 0.1
  done
  if kill -0 "${pid}" 2>/dev/null; then
    kill -KILL -- "-${pid}" 2>/dev/null || true
  fi
  wait "${pid}" 2>/dev/null || true
}

cleanup() {
  "${runsc}" kill "${container_id}" TERM >/dev/null 2>&1 || true
  "${runsc}" delete --force "${container_id}" >/dev/null 2>&1 || true
  if [[ -n ${container_pid} ]]; then
    stop_process_group "${container_pid}"
  fi
  if [[ ${store_mounted} == true ]] &&
    mountpoint -q "${instance_root}/store-merged"; then
    umount "${instance_root}/store-merged" || true
  fi
  if [[ ${endpoint_active} == true ]]; then
    "${manage_network}" remove-endpoint \
      "${network_spec}" \
      "${endpoint_index}" >/dev/null || true
  fi
  if [[ ${preparation_complete} == false && -d ${instance_root} ]]; then
    echo "prepare-container-instance: partial instance retained at ${instance_root}" >&2
  fi
}

trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

"${run_snix}" ready "${asset_root}/snix"
mkdir -p \
  "${instance_root}/bundle" \
  "${instance_root}/data" \
  "${instance_root}/nix" \
  "${instance_root}/store-upper" \
  "${instance_root}/store-work" \
  "${instance_root}/store-merged"
ln -s "${asset_root}/container-bundle/rootfs" \
  "${instance_root}/bundle/rootfs"

jq \
  --arg namespace "/run/netns/${namespace}" \
  --arg data "${instance_root}/data" \
  --arg nix "${instance_root}/nix" \
  --arg store "${instance_root}/store-merged" \
  --arg lower "${asset_root}/snix/lower" \
  '
    .process.terminal = false
    # The image initializes the Nix store for the nixbld group, then owns and
    # configures mode-0700 persistent home directories on first boot. The
    # bundle generated by umoci omits the corresponding file-management
    # capabilities that a conventional rootful OCI runtime supplies.
    | .process.capabilities |= with_entries(
        .value = (
          (
            .value
            + [
              "CAP_CHOWN",
              "CAP_DAC_OVERRIDE",
              "CAP_FOWNER",
              "CAP_SETGID",
              "CAP_SETUID"
            ]
          )
          | unique
        )
      )
    | .linux.namespaces = (
        [.linux.namespaces[] | select(.type != "network" and .type != "user")]
        + [{ type: "network", path: $namespace }]
      )
    | del(.linux.uidMappings, .linux.gidMappings)
    | .mounts = (
        [.mounts[] |
          select(
            .destination != "/data"
            and .destination != "/nix"
            and .destination != "/nix/store"
            and .destination != "/lower-store"
            and .destination != "/run"
          )]
        + [
            {
              destination: "/run",
              source: "tmpfs",
              type: "tmpfs",
              options: ["nosuid", "nodev", "mode=755", "size=16777216"]
            },
            {
              destination: "/data",
              source: $data,
              type: "bind",
              options: ["rbind", "rw", "nosuid", "nodev"]
            },
            {
              destination: "/nix",
              source: $nix,
              type: "bind",
              options: ["rbind", "rw", "nosuid", "nodev"]
            },
            {
              destination: "/nix/store",
              source: $store,
              type: "bind",
              options: ["rbind", "rw", "nosuid", "nodev"]
            },
            {
              destination: "/lower-store",
              source: $lower,
              type: "bind",
              options: ["rbind", "ro", "nosuid", "nodev", "noexec"]
            }
          ]
      )
  ' "${asset_root}/container-bundle/config.json" \
  >"${instance_root}/bundle/config.json"

"${manage_network}" create-endpoint "${network_spec}" "${endpoint_index}"
endpoint_active=true
mount -t overlay overlay \
  -o "lowerdir=${asset_root}/snix/mount,upperdir=${instance_root}/store-upper,workdir=${instance_root}/store-work,index=off" \
  "${instance_root}/store-merged"
store_mounted=true

setsid -- "${run_container}" \
  "${instance_root}/bundle" \
  "${container_id}" \
  >"${instance_root}/preparation.log" 2>&1 &
container_pid=$!

deadline=$((SECONDS + 30))
while true; do
  set +e
  status=$(curl \
    --silent \
    --noproxy '*' \
    --output "${instance_root}/response" \
    --write-out '%{http_code}' \
    --connect-timeout 1 \
    --max-time 2 \
    "http://${address}:8080/")
  curl_status=$?
  set -e
  if ((curl_status == 0)) && [[ ${status} == 200 ]]; then
    break
  fi
  kill -0 "${container_pid}" 2>/dev/null ||
    die "container exited during first-use initialization"
  ((SECONDS < deadline)) ||
    die "container did not become ready during preparation"
  sleep 0.05
done

response_sha256=$(sha256sum "${instance_root}/response")
response_sha256=${response_sha256%% *}
response_size=$(stat -c %s "${instance_root}/response")
expected_sha256=edf03332c6ca9e23cc6b21849fd76e032c59634312e1c787290816f8e8a5fa00
[[ ${response_size} -eq 25 &&
  ${response_sha256} == "${expected_sha256}" ]] ||
  die "prepared container returned the wrong response"

"${runsc}" exec "${container_id}" \
  nix store ping --store daemon \
  >"${instance_root}/nix-store-ping.log" 2>&1 ||
  die "container cannot reach its internal Nix store daemon"
"${runsc}" exec "${container_id}" \
  nix eval --expr '1 + 1' \
  >"${instance_root}/nix-eval.log" 2>&1 ||
  die "container cannot evaluate a Nix expression"

"${runsc}" kill "${container_id}" TERM >/dev/null 2>&1 || true
deadline=$((SECONDS + 10))
while kill -0 "${container_pid}" 2>/dev/null && ((SECONDS < deadline)); do
  sleep 0.1
done
"${runsc}" delete --force "${container_id}" >/dev/null 2>&1 || true
stop_process_group "${container_pid}"
container_pid=

[[ -d ${instance_root}/data/etc &&
  -d ${instance_root}/nix/var/nix ]] ||
  die "first boot did not initialize the private container state"

umount "${instance_root}/store-merged"
store_mounted=false
"${manage_network}" remove-endpoint "${network_spec}" "${endpoint_index}"
endpoint_active=false
rm -f -- "${instance_root}/response"

preparation_complete=true
echo "prepared independent container instance at ${instance_root}"
